version: '3.7'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: thiagoximenes/node
    container_name: node_server
    networks:
      - app-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    command: 'node index.js'
    depends_on:
      - db
    ports:
      - "3000:8080"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: thiagoximenes/nginx
    container_name: nginx_server
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    networks:
      - app-network

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: thiagoximenes/mysql
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=teste
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
